// import Image from "next/image";

import Head from "next/head";
import Header from "../../public/components/Header";


// export const metadata = {
//   title: "Next-hello",
//   description: "Generated by create next app",
// };
export default function Home() {

  return (
    <>
      <Header />
    </>
  );
}
